# Setup
title:        Java技术分享
tagline:      ""
baseurl:      ""
paginate:     5

# About/contact
author:
  name:       dinghuang
  url:        http://github.com/dinghuang

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown